### ISSUE TITLE
Nodes are not rotated when image (AMI) is updated

### ISSUE THREAD

**Issue by jicowan** [keikoproj/instance-manager#150] opened 2020-07-29 02:26 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**: Upgrade failed

**What you expected to happen**: Expected nodes to be replaced (rolling update)

**How to reproduce it (as minimally and precisely as possible)**: Update "image" attribute to a different AMI

**Anything else we need to know?**: 

**Environment**: EKS

- Kubernetes version: 1.17

```bash
kubectl version -o yaml
```

**Other debugging information (if applicable)**:

- InstanceGroup status:

```bash
kubectl describe instancegroup <ig-name>
```

```
Name:         instance-group
Namespace:    instance-manager
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"instancemgr.keikoproj.io/v1alpha1","kind":"InstanceGroup","metadata":{"annotations":{},"creationTimestamp":"2020-07-29T00:4...
API Version:  instancemgr.keikoproj.io/v1alpha1
Kind:         InstanceGroup
Metadata:
  Creation Timestamp:  2020-07-29T00:41:51Z
  Finalizers:
    finalizers.eks.instancegroups.keikoproj.io
  Generation:        5
  Resource Version:  22553
  Self Link:         /apis/instancemgr.keikoproj.io/v1alpha1/namespaces/instance-manager/instancegroups/instance-group
  UID:               84a40bc6-18ac-4d2c-b664-990e0bf44303
Spec:
  Eks:
    Configuration:
      Cluster Name:   keiko
      Image:          ami-0841f061f8e44c4aa
      Instance Type:  m5.large
      Key Pair Name:  eks
      Security Groups:
        sg-040260
        sg-0aa60a
      Subnets:
        subnet-
        subnet-
        subnet-
      Tags:
        Key:    kubernetes.io/cluster/keiko
        Value:  owned
      Volumes:
        Name:   /dev/xvda
        Size:   32
        Type:   gp2
    Max Size:   6
    Min Size:   3
  Provisioner:  eks
  Strategy:
    Rolling Update:
      Max Unavailable:  1
    Type:               rollingUpdate
Events:
  Type    Reason                   Age    From  Message
  ----    ------                   ----   ----  -------
  Normal  InstanceGroupCreated     23m          {"instancegroup":"instance-group","msg":"instance group has been successfully created","scalinggroup":"keiko-instance-manager-instance-group"}
  Normal  InstanceGroupNodesReady  8m37s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  6m14s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  6m3s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m53s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m43s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m32s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m22s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m11s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  5m1s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  4m51s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  4m40s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  4m30s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  4m20s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  4m9s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m59s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m48s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m38s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m28s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m17s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  3m6s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m56s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m46s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m36s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m25s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m15s        {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  2m4s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  114s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  103s         {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  93s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  83s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  72s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  61s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  51s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  41s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  31s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  20s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
  Normal  InstanceGroupNodesReady  10s          {"instancegroup":"instance-group","instances":"i-077b5471115f1a04c,i-0bcff2214e496c637,i-0eda01a48ff536b8e","msg":"instance group nodes are ready"}
```
- controller logs:

```bash
kubectl logs <instance-manager pod>
```

```
2020-07-29T02:17:33.748822573Z 2020-07-29T02:17:33.748Z	DEBUG	aws-provider	AWS API call	{"cacheHit": false, "service": "autoscaling", "operation": "TerminateInstanceInAutoScalingGroup"}
2020-07-29T02:17:33.748847803Z 2020-07-29T02:17:33.748Z	INFO	kubernetes-provider	failed to terminate targets	{"reasonError": "json: unsupported type: func() string", "scalinggroup": "keiko-instance-manager-instance-group", "targets": ["i-077b5471115f1a04c"]}
2020-07-29T02:17:33.748877794Z 2020-07-29T02:17:33.748Z	INFO	controllers.instancegroup	reconcile event ended with requeue	{"instancegroup": "instance-group", "namespace": "instance-manager", "provisioner": "eks", "resourceVersion": "22553"}
```

**Comment by eytan-avisror** [comment] 2020-07-29 15:45
Hi @jicowan 
Can you advise on the following?
- Is this consistently reproducible in your case? does it keep happening when you retry?
- What controller version are you using?
- Did you grant the controller access to TerminateInstancesInAutoScalingGroup API?

**Comment by jicowan** [comment] 2020-07-29 21:01
@eytan-avisror I have tried updating the image (AMI) twice and got similar results both times.  I did not add TerminateInstancesInAutoScalingGroup to my policy because it wasn't listed in the [directions](https://github.com/keikoproj/instance-manager/blob/master/docs/INSTALL.md) (several other APIs were missing or were wrongly named, e.g. autoscaling:CreateAutoScalingGroups has an 's' at the end).  I used [this](https://github.com/keikoproj/instance-manager/blob/master/config/crd/bases/instance-manager-deployment.yaml) to deploy the controller.  Looks like it's pulling 'latest'.

**Comment by eytan-avisror** [comment] 2020-07-29 21:03
Thanks for the clarification, looks like we need to update the documentation.
I believe if you add permissions to call that API it should work for you.

**Comment by eytan-avisror** [comment] 2020-07-29 21:04
It also seems we should correct the logging 
```
failed to terminate targets	{"reasonError": "json: unsupported type: func() string" ..
``` 
Which is not resolving the error string apparently returned from the awsErr object.

**Comment by jicowan** [comment] 2020-07-29 21:09
Adding the TerminateInstanceInAutoScalingGroup fixed this issue.  Here is the policy I am using.  Feel free to borrow: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iam:CreateInstanceProfile",
                "autoscaling:DescribeLaunchConfigurations",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "eks:DescribeNodegroup",
                "iam:PassRole",
                "iam:DetachRolePolicy",
                "autoscaling:DescribeAutoScalingGroups",
                "iam:ListAttachedRolePolicies",
                "autoscaling:UpdateAutoScalingGroup",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "iam:DeleteInstanceProfile",
                "iam:GetRole",
                "iam:GetInstanceProfile",
                "iam:DeleteRole",
                "eks:CreateNodegroup",
                "autoscaling:CreateLaunchConfiguration",
                "autoscaling:DeleteLaunchConfiguration",
                "eks:DeleteNodegroup",
                "eks:UpdateNodegroupConfig",
                "eks:DescribeCluster",
                "autoscaling:DeleteAutoScalingGroup",
                "autoscaling:CreateAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by eytan-avisror** [comment] 2020-07-29 21:27
FYI @jicowan 
The rollingUpdate strategy is pretty lacking - it does not drain and does not give much control over the pre/post wait times.
We plan to improve this in the future, however you can take a look at upgrade-manager for a more production-grade solution to upgrades.

Instance-manager can work together with upgrade-manager.

[1] Upgrade-manager: https://github.com/keikoproj/upgrade-manager
[2] CRD Strategy: https://github.com/keikoproj/instance-manager/blob/master/docs/EKS.md#crd-strategy
[3] Example: https://github.com/keikoproj/instance-manager/blob/master/test-bdd/templates/instance-group-crd.yaml#L10-L26

**Closed** 2020-07-29 23:20 UTC
Labels: bug, documentation

**Comment by jicowan** [comment] 2020-07-30 15:17
Thanks for suggestion @eytan-avisror.  I am trying to use this (or update-manager) with an EKS cluster.  I see that update manager is designed to run on the Kubernetes masters.  That's not possible with EKS.  I can create a separate node with a taint/toleration that only allows update manager to run on it mimicking the behavior of a master.  Do you have another suggestion?  Have you tested update-manager with EKS yet?

**Comment by eytan-avisror** [comment] 2020-07-30 15:32
@jicowan 
upgrade-manager can work on EKS as well, we use this setup in production on EKS (instance-manager + upgrade-manager).
You just need to run the controller elsewhere (i.e. remove the selector for master).
The upgrade-manager controller can upgrade it's own node and resume the operation when a new pod is started elsewhere.

**Comment by jicowan** [comment] 2020-07-30 16:19
@eytan-avisror thanks again.  How would you recommend using update-manager with instance-manager?  I see that you can include the 'spec' for update-manager in the instanceGroup 'spec'.  If you do that, how do you trigger an upgrade?  I don't see where you would specify a different image or instance type in the rollingUpgrade spec.

**Comment by jicowan** [comment] 2020-07-30 18:30
@eytan-avisror It appears the instance-manager cluster role has RBAC permissions to read CRDs, but I'm getting the following error: 
 
```
2020-07-30T18:23:33.619291297Z 2020-07-30T18:23:33.619Z	ERROR	controllers.instancegroup	reconcile failed	{"instancegroup": "instance-group", "provisioner": "eks", "error": "failed to process CRD strategy: failed to discover active custom resources: rollingupgrades.upgrademgr.keikoproj.io is forbidden: User \"system:serviceaccount:instance-manager:instance-manager\" cannot list resource \"rollingupgrades\" in API group \"upgrademgr.keikoproj.io\" in the namespace \"instance-manager\"", "errorVerbose": "rollingupgrades.upgrademgr.keikoproj.io is forbidden: User \"system:serviceaccount:instance-manager:instance-manager\" cannot list resource \"rollingupgrades\" in API group \"upgrademgr.keikoproj.io\" in the namespace \"instance-manager\"\nfailed to discover active custom resources\ngithub.com/keikoproj/instance-manager/controllers/providers/kubernetes.ProcessCRDStrategy\n\t/workspace/controllers/providers/kubernetes/crd.go:73\ngithub.com/keikoproj/instance-manager/controllers/provisioners/eks.(*EksInstanceGroupContext).UpgradeNodes\n\t/workspace/controllers/provisioners/eks/upgrade.go:40\ngithub.com/keikoproj/instance-manager/controllers.HandleReconcileRequest\n\t/workspace/controllers/interface.go:58\ngithub.com/keikoproj/instance-manager/controllers.(*InstanceGroupReconciler).Reconcile\n\t/workspace/controllers/instancegroup_controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nfailed to process CRD strategy\ngithub.com/keikoproj/instance-manager/controllers/provisioners/eks.(*EksInstanceGroupContext).UpgradeNodes\n\t/workspace/controllers/provisioners/eks/upgrade.go:44\ngithub.com/keikoproj/instance-manager/controllers.HandleReconcileRequest\n\t/workspace/controllers/interface.go:58\ngithub.com/keikoproj/instance-manager/controllers.(*InstanceGroupReconciler).Reconcile\n\t/workspace/controllers/instancegroup_controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}
```

Here is the cluster role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"creationTimestamp":null,"name":"instance-manager"},"rules":[{"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["create","get","list","patch","update","watch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","get","list","watch"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["list","patch","watch"]},{"apiGroups":["instancemgr.keikoproj.io"],"resources":["instancegroups"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["instancemgr.keikoproj.io"],"resources":["instancegroups/status"],"verbs":["get","patch","update"]}]}
  creationTimestamp: "2020-07-28T22:57:01Z"
  name: instance-manager
  resourceVersion: "2493"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/instance-manager
  uid: c3b80c8b-8067-4713-aff8-1b147b6bd1cb
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - patch
  - watch
- apiGroups:
  - instancemgr.keikoproj.io
  resources:
  - instancegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instancemgr.keikoproj.io
  resources:
  - instancegroups/status
  verbs:
  - get
  - patch
  - update
```

**Comment by jicowan** [comment] 2020-07-30 18:51
Had to add to the instance-manager clusterrole: 
```
- apiGroups:
  - upgrademgr.keikoproj.io
  resources:
  - rollingupgrades
  verbs:
  - list
  - get
```

**Comment by eytan-avisror** [comment] 2020-07-30 18:51
@jicowan Yes, since the crd strategy is generic we did not add the role required for RollingUpgrades specifically in the documentation, but you need to grant the controller permissions to get, list, create, delete the resource you want to submit. example in the case of upgrade-manager:
```
- apiGroups:
  - upgrademgr.keikoproj.io
  resources:
  - rollingupgrades
  verbs:
  - get
  - list
  - create
  - delete
```

**Comment by jicowan** [comment] 2020-07-30 19:00
Last comment.  Have you run into [this](https://github.com/kubernetes/kubernetes/pull/90823) issue during node upgrades with upgrade-manager?  Do you think you can handle this with a preDrain script?

**Comment by eytan-avisror** [comment] 2020-07-30 19:09
We use alb-ingress-controller, not sure if it will help in your case / if I understand the issue exactly, but I think lifecycle-manager (see project under keiko) might help you in this case. It uses lifecycle hooks to drain ELB/ALB and adds the exclusion label to nodes when they get terminated.
